      - name: Створити .gitignore
        run: |
          cat > .gitignore << 'EOF'
          __pycache__/
          *.py[cod]
          *.pyo
          *.pyd
          *.swp
          *.bak
          *.tmp
          *.log
          .venv/
          env/
          venv/
          .DS_Store
          Thumbs.db
          .vscode/
          .idea/
          htmlcov/
          .tox/
          .coverage
          coverage.xml
          .pytest_cache/
          *.workflow.log
          epg*.bak
          epg*.old
          EOF

      - name: Commit & PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Додано .gitignore"
          branch: epg-bot
          title: "Додано .gitignore"
          body: "Автоматичний додаток `.gitignore` для очищення репозиторію"
          base: main
          # видаляє гілку після злиття
          delete-branch: true
